### ISSUE TITLE
Add support for push notifications on the Android platform.

### ISSUE THREAD

**Issue by coreymcmahon** [capacitor-community/intercom#34] opened 2021-07-07 09:28 UTC
**Is your feature request related to a problem?**

Push notifications seem not to be supported on the Android platform for this plugin. 

Push notifications are a key part of any livechat integration as the user is likely to close/background the app after sending a message via the Intercom widget, and experiences with other chat platforms (e.g Facebook Messenger, WhatsApp, LINE, etc.) have set the expectation that a new message will be accompanied by a device-native push alert. It's a very unexpected and disappointing experience for the user if they need to constantly re-open the app and check the Intercom page for a new message (especially for real-time ecommerce).

This limitation is not currently referenced in the README file. As a result we had to abandon our integration efforts with this plugin half-way through and migrate to the Cordova plugin.

---

**Describe the solution you'd like**

This already seems to be implemented for iOS, the Android implementation should be very similar.

This plugin assumes the Capacitor Push plugin is used to register the user's device token for push notifications. When the application calls `.register()`...

![image](https://user-images.githubusercontent.com/700486/124733448-662b1d00-df3e-11eb-92ea-6900842626ac.png)

... the device token is fetched. If successful, the `registration` event is raised and any associated listeners are executed:

![image](https://user-images.githubusercontent.com/700486/124733570-83f88200-df3e-11eb-8e4f-b44240b3f9de.png)

A listener should be added to this event which captures the token and forwards to the Intercom native Android SDK. You can see this exact behaviour is implemented already in the iOS version:

![image](https://user-images.githubusercontent.com/700486/124733670-9e326000-df3e-11eb-8ee9-4a73016da8df.png)

Something similar should be implemented here on the Android version:

![image](https://user-images.githubusercontent.com/700486/124733741-ae4a3f80-df3e-11eb-8edb-653a68fe8a5a.png)

In the meantime it would be useful if the README could be updated to communicate this limitation of the plugin.

**Comment by therealsquidgee** [comment] 2021-08-19 08:08
+1 it was a bit of a nasty surprise to implement the plugin only to realise Push Notifications do not work on Android.

**Comment by asangadev** [comment] 2021-09-04 00:28
It's really cool if we can have this on Android!

**Comment by asangadev** [comment] 2021-09-05 06:11
**Update:** I managed to send the `PUSH TOKEN` to intercom via this method:

`intercomPushClient.sendTokenToIntercom(this.getActivity().getApplication(), token);`

I have created a custom method to pass the token to intercom:

```
PushNotifications.register()

PushNotifications.addListener('registration', token => {
      intercom.setUserToken({
        user: token.value
      })
 })
```

Now I can see the user is subscribed to push messages. But still not receiving the push messages. 

<img width="370" alt="Screen Shot 2021-09-05 at 4 07 34 pm" src="https://user-images.githubusercontent.com/16328655/132117315-f03502df-4ff8-4cf3-a88b-6ac50ced7d76.png">

**Comment by asangadev** [comment] 2021-09-17 09:52
We have added these features here: https://github.com/Fiksuruoka-fi/capacitor-intercom

**Comment by stewones** [comment] 2021-10-12 01:08
you might be doing something wrong, push notifications for android were always present in this plugin. it doesn't require any step in the plugin initialization. closing as I can't reproduce your issue.

**Closed by stewones** 2021-10-12 01:08 UTC

**Comment by jpike88** [comment] 2024-11-06 05:37
This is still an ongoing issue for us. I think the key different is that in the Cordova implementation, they've addressed FCM installations here:

https://github.com/intercom/intercom-cordova/blob/eb5d78a07f83c1986e8d34ab7ca4d5ed10a40b6a/intercom-plugin/src/android/IntercomBridge.java#L85

Please reopen this issue @jcesarmobile as it's ongoing and needs to be properly addressed

**Comment by jpike88** [comment] 2024-11-06 07:40
I've figured out a solution that works, see my branch here, I've mangled a few files to ensure it works properly but it works. I'll leave this to the maintainers to learn from it and implement it in a way that's suitable for them

https://github.com/aquipa/capacitor-intercom/pull/1
